### ISSUE TITLE
Feedback on week 12 project progress for CS2113-T14-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-2/main#115]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline 2019-11-13 set(:exclamation: try to do by next milestone)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113-T14-2/main/pull/113 https://github.com/AY1920S1-CS2113-T14-2/main/pull/111 https://github.com/AY1920S1-CS2113-T14-2/main/issues/109 https://github.com/AY1920S1-CS2113-T14-2/main/issues/107 https://github.com/AY1920S1-CS2113-T14-2/main/issues/106 https://github.com/AY1920S1-CS2113-T14-2/main/issues/105 (:heavy_check_mark: well done!)
## Individual progress of @saradj for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-2/main/issues/109 https://github.com/AY1920S1-CS2113-T14-2/main/issues/107 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @x3chillax for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-2/main/issues/107 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ceglincoln for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-2/main/pull/113 https://github.com/AY1920S1-CS2113-T14-2/main/pull/111 https://github.com/AY1920S1-CS2113-T14-2/main/issues/109 https://github.com/AY1920S1-CS2113-T14-2/main/issues/105 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @9hafidz6 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-2/main/issues/109 https://github.com/AY1920S1-CS2113-T14-2/main/issues/105 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @virginiayu for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-2/main/issues/106 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @sanjukta99

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-07 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
